---
language: ruby
cache: bundler
sudo: false
rvm: 2.4
bundler_args: --path vendor
notifications:
  email: false

stages:
  - syntax
  - spec
  - acceptance

before_install:
  - rm -f Gemfile.lock
  - rm -f inspec.lock

before_script:
  - bundle exec inspec vendor --overwrite

jobs:
  fast_finish: true

  include:
    - stage: syntax
      script:
        - bundle exec ruby -c controls/*.rb libraries/*.rb

    - stage: spec
      script:
        - bundle exec rake profile:check

    - stage: acceptance
      sudo: required
      services:
        - docker
      script:
        - bundle exec rake beaker:suites[default,docker]
