---
language: ruby

notifications:
  email: false

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - inspec

before_install:
  - rm -f Gemfile.lock
  # Unvendor
  - rm -f inspec.lock
  - rm -rf vendor

before_script:
  - bundle exec inspec vendor --overwrite

jobs:
  fast_finish: true

  include:
    - stage: syntax
      sudo: false
      rvm: 2.4
      script:
        - bundle exec ruby -c controls/*.rb libraries/*.rb

    - stage: spec_test
      sudo: false
      rvm: 2.4
      script:
        - bundle exec rake profile:check

    - stage: system_test
      sudo: required
      services:
        - docker
      rvm: 2.4
      script:
        - bundle exec rake beaker:suites[default,docker]
